FROM node:20-alpine AS builder
WORKDIR /app
COPY apps/backend/package.json ./
RUN npm install
COPY apps/backend .
RUN npm run build

FROM node:20-alpine
WORKDIR /app
COPY --from=builder /app/.output ./.output
COPY --from=builder /app/package.json ./package.json
RUN npm install --omit=dev

EXPOSE 3001
ENV NODE_ENV=production
CMD ["node", ".output/server/index.mjs"]
