<template><div class="max-w-5xl mx-auto p-5 sm:p-8" v-if="server">
  <div class="flex flex-wrap items-start justify-between gap-4"><div><p class="text-dark-400 text-sm">{{ labels[server.type] }} · Minecraft {{ server.mc_version }}</p><h1 class="text-3xl font-bold text-white mt-1">{{ server.name }}</h1></div><div class="flex gap-2"><button v-if="server.status==='stopped' || server.status==='error'" class="button primary" @click="run(start)">▶ เริ่ม</button><button v-if="server.status==='running'" class="button secondary" @click="run(restart)">↻ รีสตาร์ต</button><button v-if="server.status==='running'" class="button danger" @click="run(stop)">■ หยุด</button></div></div>
  <p v-if="error" class="mt-4 text-red-300 text-sm">{{ error }}</p>
  <div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-8"><div class="card"><span>สถานะ</span><ServerStatus :status="server.status" class="mt-2" /></div><div class="card"><span>พอร์ต</span><b class="font-mono text-white">:{{ server.port }}</b></div><div class="card"><span>หน่วยความจำ</span><b class="text-white">{{ server.memory_mb }} MB</b></div><div class="card"><span>ผู้เล่นสูงสุด</span><b class="text-white">{{ server.max_players }}</b></div></div>
  <section class="mt-6 bg-dark-900 border border-dark-700 rounded-2xl p-5"><h2 class="text-white font-semibold">การจัดการ</h2><div class="grid sm:grid-cols-3 gap-3 mt-4"><NuxtLink :to="`/servers/${server.id}/settings`" class="action">⚙️ <span><b>ตั้งค่า</b><small>{{ server.status === 'stopped' ? 'แก้ไขได้ขณะหยุด' : 'หยุดก่อนจึงแก้ไขได้' }}</small></span></NuxtLink><NuxtLink :to="`/servers/${server.id}/console`" class="action">💻 <span><b>คอนโซล</b><small>ดู Log และส่งคำสั่ง</small></span></NuxtLink><NuxtLink :to="`/servers/${server.id}/files`" class="action">📁 <span><b>ไฟล์</b><small>อัปโหลด แก้ไข แตก ZIP</small></span></NuxtLink></div></section>
  <section v-if="server.status==='running'" class="mt-6 bg-dark-900 border border-dark-700 rounded-2xl p-5"><div class="flex justify-between"><h2 class="text-white font-semibold">ทรัพยากร</h2><span class="text-dark-500 text-xs">อัปเดตอัตโนมัติ</span></div><div class="grid grid-cols-2 gap-4 mt-4"><div><span class="text-dark-400 text-sm">CPU</span><p class="text-xl font-semibold text-white">{{ stats.cpuPercent }}%</p></div><div><span class="text-dark-400 text-sm">Memory</span><p class="text-xl font-semibold text-white">{{ stats.memoryMB }} MB</p></div></div></section>
</div><div v-else class="p-8 text-dark-400">กำลังโหลด…</div></template>
<script setup lang="ts">
definePageMeta({ layout:'server' }); const route=useRoute(); const store=useServersStore(); const id=route.params.id as string; const server=computed(()=>store.servers.find(s=>s.id===id)); const error=ref(''); const stats=ref({cpuPercent:0,memoryMB:0}); const labels:Record<string,string>={vanilla:'Vanilla',fabric:'Fabric',forge:'Forge',neoforge:'NeoForge',paper:'Paper',spigot:'Spigot',bukkit:'Bukkit',curseforge:'CurseForge'}
async function run(fn:()=>Promise<any>){ error.value=''; try { await fn(); await store.fetchServer(id) } catch(e:any){error.value=e?.data?.statusMessage||'ทำรายการไม่สำเร็จ'} }; const start=()=>store.startServer(id); const stop=()=>store.stopServer(id); const restart=()=>store.restartServer(id)
async function loadStats(){if(server.value?.status==='running') stats.value=await $fetch(`/api/servers/${id}/stats`).catch(()=>stats.value) as any}; onMounted(async()=>{await store.fetchServer(id); await loadStats(); setInterval(loadStats,5000)})
</script><style scoped>.card{ @apply rounded-xl bg-dark-900 border border-dark-700 p-4 flex flex-col gap-1; }.card span{ @apply text-sm text-dark-400; }.action{ @apply flex gap-3 items-center rounded-xl bg-dark-800 hover:bg-dark-750 border border-dark-700 p-4 text-xl; }.action span{ @apply flex flex-col text-sm; }.action b{ @apply text-white font-medium; }.action small{ @apply text-dark-500 mt-1; }.button{ @apply rounded-xl px-4 py-2.5 font-medium text-sm transition-colors; }.primary{ @apply bg-mc-green hover:bg-green-300 text-dark-950; }.secondary{ @apply bg-dark-700 hover:bg-dark-600 text-white; }.danger{ @apply bg-red-600 hover:bg-red-500 text-white; }</style>
